config/routes.rb
Rails.application.routes.draw do
  get '/todos/list', to: 'todos#list', as: 'lista/todos'
  #resources :todos
  get '/todos', to: 'todos#index'
  get '/todos/new', to: 'todos#new', as: 'new/todos'
  post '/todos', to: 'todos#create', as: 'create/todos'
  get '/todos/:id', to: 'todos#show', as: 'todo'
  get '/todo/:id/edit', to: 'todos#edit', as: 'edit_todo'
  patch '/todos/:id', to: 'todos#update'
  delete '/todos/:id', to: 'todos#destroy', as: 'delete/todo'
  patch '/todos/:id/complete', to: 'todos#complete', as: 'complete/todos'
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'todos#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/todo.rb
class Todo < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/todos_controller.rb
class TodosController < ApplicationController
    before_action :set_todos, only: %i(show edit update destroy complete)
    
    def index
        @todos = Todo.order(:id)
    end

    def new
        @todo = Todo.new
    end

    def create
        todo = Todo.new(todo_params)
        todo.save
        redirect_to root_path, notice: 'ToDo add correctly!'
    end

    def show
        
    end 

    def edit
        
    end 

    def update
        
        @todo.update(todo_params)
        redirect_to root_path, notice: 'Description Update Successful'
    end 

    def destroy
        
        @todo.destroy
        redirect_to root_path, notice: 'Delete Sucessful'
    end 

    def complete
        
        @todo.completed = true
        @todo.save
        redirect_to root_path, notice: 'Congratulations!!!!!!!'
    end

    def list
        @completed_todos = Todo.where(completed: true)
        @uncompleted_todos = Todo.where(completed: false)
    end

    private

    def set_todos
        @todo = Todo.find(params[:id])
    end

    def todo_params
        
        params.require(:todo).permit(:description)

    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/todos_helper.rb
module TodosHelper
end

app/views/layouts/_nav.html.erb
  <nav class="navbar navbar-expand-lg navbar-light bg-light fixed-top">
  <a class="navbar-brand" href="#">ToDO!</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav">
      <li class="nav-item active">
        <a class="nav-link" href=" <%= asset_path root_path %> ">Home</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href=" <%= asset_path lista_todos_path %> ">List</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href=" <%= asset_path new_todos_path %> ">New ToDo</a>
      </li>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TodoApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css" integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS" crossorigin="anonymous">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
<%= render 'layouts/nav' %>

<br> <!-- Es es culpa del JP :| -->
<br>
<br>
    <div class="container">
      <%= yield %>
    </div>
    
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js" integrity="sha384-wHAiFfRlMFy6i5SRaxvfOCifBUQy1xHdJ/yoi7FRNXMRBu5WHdZYu1hA6ZOblgut" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js" integrity="sha384-B0UglyR+jN6CkvvICOB2joaf5I4l3gm9GU6Hc1og6Ls7i6U/mkkaduKaBhlAXv9k" crossorigin="anonymous"></script>
  </body>
</html>

app/views/todos/_form.html.erb
<%= form_with(model: @todo, local: true) do |todo| %>


  <div class="form-group">
   <%= todo.label :description %>
   <%= todo.text_field :description, class: 'form-control' %> 
  </div>
    <%= todo.submit 'Send', class: 'btn btn-primary' %>
 
 
 <% end %>

app/views/todos/edit.html.erb
<h1>SOY EL EDIT</h1>
<br>

<%= render 'todos/form' %>

 <br>

 <%= link_to 'Back', root_path %>

app/views/todos/index.html.erb
<h1>SOY EL INDEX</h1>
<br>
<%= notice %>
<br><br>
<%= link_to 'Creat New ToDo', new_todos_path %>
<br><br>
<ul class="list-group">

    <% @todos.each do |todo| %>

     <li class="list-group-item"> <%= todo.description %> - <%= link_to 'COMPLETED!', complete_todos_path(todo), method: :patch %> - <%= link_to 'Show', todo_path(todo) %> - <%= link_to 'Edit', edit_todo_path(todo) %> - <%= link_to 'Delete', delete_todo_path(todo), method: :delete %></li>
  
    <% end %>
  
</ul>

app/views/todos/list.html.erb
<h1>SOY LA LISTA</h1>

<div class="row">
    <div class="col-sm-6" style="background-color:lavender;"> <h3>Not Completed</h3>
    <div style="background-color:lavender;">
        <div class="col-12 col-md-12 col-lg-12">
        <ul>
        <% @uncompleted_todos.each do |incompletos| %>
            
            <li><%= incompletos.description %></li>
        
        <% end %>
        
        </ul>
        </div>
    </div>
    </div>
    <div class="col-sm-6" style="background-color:lavenderblush;"><h3>Completed</h3>
        <div style="background-color:lavenderblush;">
            <div class="col-12 col-md-12 col-lg-12">
                <ul>
                    <% @completed_todos.each do |completos| %>
            
                        <li><%= completos.description %></li>
        
                    <% end %>
        
                </ul>
            </div>
        </div>
    </div>
    </div>
    <%= link_to 'Back', root_path %>
</div>  

app/views/todos/new.html.erb
<h1>SOY EL NEW</h1>

<%= render 'todos/form' %>

 <br>

 <%= link_to 'Back', root_path %>
 

app/views/todos/show.html.erb
<h1>SOY EL SHOW</h1>
<br>
Descripcion: <%= @todo.description %> <br>
Completed? <%= @todo.completed %> <br>

<%= link_to 'Back', root_path %>